version: '3'
services:
  juice-shop:
    container_name: juice-shop
    image: bkimminich/juice-shop
    restart: always
    # Safety override
    environment:
      NODE_ENV: "unsafe"
    ports:
      - "3000:3000"
    networks:
      vulnurable:
        ipv4_address: 10.0.0.4
  dvwa:
    container_name: dvwa
    image: vulnerables/web-dvwa
    restart: always
    ports:
      - "3001:80"
    networks:
      vulnurable:
        ipv4_address: 10.0.0.5
  mutillidae:
    container_name: mutillidae
    image: bltsec/mutillidae-docker
    restart: always
    ports:
      - "3002:80"
    networks:
      vulnurable:
        ipv4_address: 10.0.0.6
networks:
  vulnurable:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
        gateway: 10.0.0.1
