version: '3'
services:
  downloader:
    container_name: downloader
    # manually imported image
    image: downloader:v1
    restart: always
    volumes:
      - "/srv/dev-disk-by-uuid-dc414ea1-c74d-4893-98b3-ffb607641d12/Movies:/usr/src/downloader/downloads"
    ports:
      - 5000:5000
    environment:
      DOCKER: 1
    network_mode: host