version: '3.8'
services:  
  # ----------------------------------------------------------------------
  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 3670:8080
    volumes:
      - "${HOME}/Movies:/data/Movies"
      - "${HOME}/DBS:/data/Configs"
      - "${HOME}/DBS/fb_config:/config"
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
  # ----------------------------------------------------------------------
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    user: "${UID}:${GID}"
    volumes:
      - "${HOME}/Movies/Books:/manga"
      - "${HOME}/DBS/kavita_conf:/kavita/config"
    ports:
      - "5001:5000"
    restart: always
  # ----------------------------------------------------------------------
  dashy:
    container_name: dashy
    image: lissy93/dashy
    restart: always
    environment:
      - NODE_ENV=production
      - UID=${UID}
      - GID=${GID}
    ports:
      - "5002:80"
    volumes:
      - "${HOME}/DBS/dashy_conf:/app/public"
  # ----------------------------------------------------------------------
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=Europe/Kiev
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=boddicheg
      - POSTGRES_PASSWORD=${DB_PSK}
      - POSTGRES_HOST=${HOST}
      - POSTGRES_PORT=5440
      - NEXTCLOUD_ADMIN_USER=boddicheg
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - REDIS_HOST=${HOST}
      - REDIS_HOST_PORT=6379
    volumes:
      - "${HOME}/DBS/nextcloud_config:/config"
      - "${HOME}/NextCloud:/data"
    ports:
      - 3004:80
      - 8443:443
    restart: unless-stopped
  # ----------------------------------------------------------------------
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "5003:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"          # YOUR INITIAL ADMIN PASSWORD (MINIMUM 8 CHARACTERS, USERNAME "admin")
      PHOTOPRISM_SITE_URL: "http://${HOST}:2342/"  # public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_PUBLIC: "false"                     # no authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables storage permission updates on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables facial recognition
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW files
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW files (reduces performance)
      PHOTOPRISM_JPEG_QUALITY: 85                    # image quality, a higher value reduces compression (25-100)
      PHOTOPRISM_DETECT_NSFW: "false"                # flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "${HOST}:3307"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "${DB_PSK}"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""                # meta site description
      PHOTOPRISM_SITE_AUTHOR: ""                     # meta site author

      PHOTOPRISM_UID: ${UID}
      PHOTOPRISM_GID: ${GID}

    working_dir: "/photoprism"
    volumes:
      - "${HOME}/Movies/Pics/Original:/photoprism/originals"
      - "${HOME}/Movies/Pics/Storage:/photoprism/storage"
      - "${HOME}/NextCloud/boddicheg/files:/photoprism/originals/family"
  # ----------------------------------------------------------------------
  joplin:
    image: joplin/server:latest
    container_name: joplin
    ports:
    - "5010:22300"
    restart: unless-stopped
    environment:
      APP_PORT: 5010
      APP_BASE_URL: "http://${HOST}:5010"
      DB_CLIENT: pg
      POSTGRES_PASSWORD: ${DB_PSK}
      POSTGRES_DATABASE: joplin_db
      POSTGRES_USER: boddicheg
      POSTGRES_PORT: 5445
      POSTGRES_HOST: ${HOST}
      MAX_TIME_DRIFT: 0
    network_mode: host
    #user: "${UID}:${GID}"
  #----------------------------------------------------
  aria2ng:
    image: hurlenko/aria2-ariang
    container_name: aria2ng
    ports:
      - 8080:8080
    volumes:
      - "${HOME}/Movies/:/aria2/data"
      - "${HOME}/DBS/aria2ng-config/:/aria2/conf"
    environment:
      - PUID=1000
      - PGID=100
      - ARIA2RPCPORT=443
    restart: always