version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5005:80/tcp"
    environment:
      TZ: 'Europe/Kiev'
    volumes:
      - "${HOME}/pihole/etc-pihole:/etc/pihole"
      - "${HOME}/pihole/etc-dnsmasq:/etc/dnsmasq.d"
    restart: unless-stopped